name: AdminInventoryTools
version: 1.0.1
main: net.jp.minecraft.plugin.Main
commands:
    ait:
        description: Provides a Admin GUI for administrators.
        usage: /ait
        permission: ait.give
        permission-message: You don't have permission (ait.give)
permissions:
    ait.open:
        description: Allow open Admin GUI.
        default: op
    ait.give:
        description: Give a Admin GUI stick.
        default: op
