name: AdminInventoryTools
version: 1.0.0
main: net.jp.minecraft.plugin.Main
permissions:
    ait.open:
        description: Allow open Admin GUI.
        default: op
    ait.give:
        description: Give a Admin GUI stick.
        default: op
commands:
    ait:
        description: Provides a Admin GUI for administrators.
        usage: You don't have a permisson (ait.give)
